laparagon/account/urls.py
from django.urls import path

from . import views

app_name = 'account'
urlpatterns = [
    #path('', views.profile_page, name='collection'),
    path('register/', views.register, name='register'),
    #path('profile/', views.profile_page, name='profile'),
    path('profile/collection/', views.collection_page, name='collection'),
    path('profile/wishlist/', views.wishlist_page, name='wishlist'),

    path('add/<slug:type_slug>/<slug:toy_slug>/', views.add_to_profile, name='add_to_profile'),
    path('remove/<slug:toy_slug>/', views.remove_from_collection, name='remove_from_collection'),
]

laparagon/authentication/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'authentication'
urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='authentication/logout.html'), name="logout"),
    # register
]




laparagon/gallery/urls.py
from django.urls import path

from . import views

app_name = 'gallery'

urlpatterns = [
    path('art_toy/', views.art_toy_page, name='art_toy'),
    path('art_toy/<slug:toy_slug>/', views.art_toy_detail, name='art_toy_detail'),
    path('art_toy_search/', views.art_toy_search, name='art_toy_search'),

    path('artist/', views.artist_page, name='artist'),
    path('artist/<slug:artist_slug>/', views.artist_detail, name='artist_detail'),
    path('artist_search/', views.artist_search, name='artist_search'),

    #path('base_model/', views.base_model_page, name='base_model'),
    path('base_model/<slug:base_slug>/', views.base_model_detail, name='base_model_detail'),

    path('organization/<slug:org_slug>/', views.organization_detail, name='organization_detail'),
    # path('artist/<slug:artist_slug>/', views.artist_detail, name='artist_detail'),
    # path('artist/<slug:artist_slug>/', views.artist_detail, name='artist_detail'),
]

laparagon/paragon/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('home/', views.home, name='home'),
    path('about/', views.about_us, name='about_us'),
    # Apps
    path('gallery/', include('gallery.urls')),
    path('authentication/', include('authentication.urls')),
    path('account/', include('account.urls')),
    # Admin
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

laparagon/templates/about_us.html
{% extends "base_site.html" %}
{% load static %}

{% block title %} | About Us {% endblock title%}

{% block content %}
<div class="row indigo lighten-5">
  <div class="col s12 center">
    <h4 class="black-text"><b>About Us</b></h4>
  </div>
</div>

<!-- About Us Content -->
<div class="container">
  <div class="section">
    <div class="row">
      <div class="col s12 center">
        <p class="flow-text">
          The idea to create <b> Paragon Art Toys</b> came to us when we were just starting out to collect art toys. We had a hard time looking for existing pieces on social media, as well as having limited awareness of some of the artists and their work. We want to help old and aspiring collectors keep up to date with art toys and find more that will fit our preference. We also want to help artists showcase their work and connect with other artists, paving the way for collaboration.
        </p>
      </div>
    </div>
  </div>
</div>

<!-- Banner -->
<div class="parallax-container valign-wrapper">
<div class="section no-pad-bot">
  <div class="container">
    <div class="row center">
      <h5 class="header col s12 light"></h5>
    </div>
  </div>
</div>
<div class="parallax"><img src="{% static 'common/background3.jpg' %}" alt="Unsplashed background img 3"></div>
</div>
{% endblock content %}

laparagon/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>

  <!-- CSS  -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="{% static 'common/css/materialize.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link href="{% static 'common/css/style.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

  <!-- Tab Content -->
  <title> Paragon {% block title %} {% endblock %}</title>
  <link rel="shortcut icon" href="{% static 'common/p.png' %}">
</head>

<body >
  <!-- Nav content -->
  {% block nav %}
  {% endblock %}

  <!-- Message Content -->
  {% if messages %}
    {% for message in messages %}
      <div class="alert alert-{{ message.tags }}">
         {{ message }}
      </div>
    {% endfor %}
  {% endif %}

  <!-- Main Content -->
  {% block content %}
  {% endblock %}

  <!-- Footer Content -->
  {% block footer %}
  {% endblock %}

  <!--  Scripts-->
  <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script src="{% static 'common/js/materialize.js' %}"></script>
  <script src="{% static 'common/js/init.js' %}"></script>

  </body>
</html>

laparagon/templates/base_site.html
{% extends "base.html" %}
{% load static %}

{% block nav %}
<!-- Navbar -->
<div class="navbar-fixed">
  <nav class="black" role="navigation">
    <div class="nav-wrapper container">
      <!-- Nav Logo -->
      <a id="logo-container" href="{% url 'home' %}" class="brand-logo">
        <img class="responsive-img" src="{% static 'common/paragon_logo.png' %}" alt="banner" height="110" width="160">
      </a>
      <ul class="right hide-on-med-and-down">
        <!-- Global Search Bar -->
        <li>
          <form method="GET" action="{% url 'gallery:art_toy_search' %}">
            <div class="input-field">
              <input id="search" type="search" name="q" placeholder="Search by art toy or artist" value="{{ request.GET.q }}" required>
              <label class="label-icon" for="search"><i class="material-icons">search</i></label>
              <i class="material-icons">close</i>
            </div>
          </form>
        </li>
        <!-- Nav Tabs -->
        <li class="{% if nbar == 'home' %}grey darken-3{% endif %}">
          <a href="{% url 'home' %}" class="white-text"><b>Home</b></a>
        </li>
        <li class="{% if nbar == 'art_toy' %}grey darken-3{% endif %}">
          <a href="{% url 'gallery:art_toy' %}" class="white-text "><b>Art Toys</b></a>
        </li>
        <li class="{% if nbar == 'artist' %}grey darken-3{% endif %}">
          <a href="{% url 'gallery:artist' %}" class="white-text"><b>Artists</b></a>
        </li>
        <li class="{% if nbar == 'about_us' %}grey darken-3{% endif %}">
          <a href="{% url 'about_us' %}" class="white-text"><b>About Us</b></a>
        </li>
        <!-- Log in or dropdown -->
        <li class="{% if nbar == 'login' %}grey darken-3{% endif %}">
          {% if user.is_authenticated %}
            <!-- Dropdown Trigger -->
            <a class="dropdown-trigger black orange-text" href="#!" data-target="nav1">
              <b>{{user.username}}</b>
              <i class="material-icons right">arrow_drop_down</i>
            </a>
            <!-- Dropdown Structure -->
            <ul id='nav1' class='dropdown-content black'>
              <li><a class="orange-text disabled" href=#">{{ request.user }}</a></li>
              <li class="divider grey darken-3" tabindex="-1"></li>
              <li><a class="orange-text" href="{% url 'account:collection' %}">Profile</a></li>
              <li class="divider grey darken-3" tabindex="-1"></li>
              <li><a class="orange-text" href="{% url 'authentication:logout' %}">Logout</a></li>
            </ul>
          {% else %}
            <a href="{% url 'authentication:login' %}" class="orange-text hoverable"><b>Log In</b></a>
          {% endif %}
        </li>
      </ul>
      <!-- Button for Mobile Menu -->
      <a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons purple-text darken-2">menu</i></a>
    </div>
  </nav>
</div>

<!-- Navbar Mobile -->
<div class="nav-wrapper container">
  <ul id="nav-mobile" class="sidenav black">
    <!-- Global Search Bar -->
    <li>
      <form method="GET" action="{% url 'gallery:art_toy_search' %}">
        <div class="input-field">
          <input id="search" type="search" name="q" placeholder="Search by art toy or artist" value="{{ request.GET.q }}" required>
          <label class="label-icon" for="search"><i class="material-icons">search</i></label>
          <i class="material-icons">close</i>
        </div>
      </form>
    </li>
    <!-- Nav Tabs -->
    <li class="{% if nbar == 'home' %}grey darken-3{% endif %}">
      <a href="{% url 'home' %}" class="white-text"><b>Home</b></a>
    </li>
    <li class="{% if nbar == 'art_toy' %}grey darken-3{% endif %}">
      <a href="{% url 'gallery:art_toy' %}" class="white-text "><b>Art Toys</b></a>
    </li>
    <li class="{% if nbar == 'artist' %}grey darken-3{% endif %}">
      <a href="{% url 'gallery:artist' %}" class="white-text"><b>Artists</b></a>
    </li>
    <li class="{% if nbar == 'about_us' %}grey darken-3{% endif %}">
      <a href="{% url 'about_us' %}" class="white-text"><b>About Us</b></a>
    </li>
    <!-- Log in or dropdown -->
    <li class="{% if nbar == 'login' %}grey darken-3{% endif %}">
      {% if user.is_authenticated %}
        <!-- Dropdown Trigger -->
        <a class="dropdown-trigger black orange-text" href="#!" data-target="nav2">
          <b>{{user.username}}</b>
          <i class="material-icons right">arrow_drop_down</i>
        </a>
        <!-- Dropdown Structure -->
        <ul id='nav2' class='dropdown-content black'>
          <li><a class="orange-text disabled" href=#">{{ request.user }}</a></li>
          <li class="divider grey darken-3" tabindex="-1"></li>
          <li><a class="orange-text" href="{% url 'account:collection' %}">Profile</a></li>
          <li class="divider grey darken-3" tabindex="-1"></li>
          <li><a class="orange-text" href="{% url 'authentication:logout' %}">Logout</a></li>
        </ul>
      {% else %}
        <a href="{% url 'authentication:login' %}" class="orange-text hoverable"><b>Log In</b></a>
      {% endif %}
    </li>
  </ul>
</div>
{% endblock nav %}

<!-- Footer -->
{% block footer %}
<footer class="page-footer black">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Bio</h5>
        <p class="grey-text text-lighten-4">BABAGANUSH</p>
      </div>
    </div>
  </div>
  <div class="footer-copyright grey darken-3">
    <div class="container">
      Developed by <a class="brown-text text-lighten-3" href="https://www.facebook.com/lanz.cu/" target="_blank" >Lanz Cu</a>
    </div>
  </div>
</footer>
{% endblock footer %}

laparagon/templates/home.html
{% extends "base_site.html" %}
{% block title %} | Home {% endblock %}
{% load static %}

{% block content %}

<!-- Main Page Banner -->
<div id="index-banner" class="parallax-container">
  <div class="section no-pad-bot">
    <div class="container">
      <br><br>
      <b><h1 class="header center orange-text ">
        {% if user.is_authenticated %}
          Welcome back {{ request.user }}
        {% else %}
          Welcome to Paragon Art Toys!
        {% endif %}
      </h1></b>
      <div class="row center">
        {% if user.is_authenticated %}
          <b><a href="#" class="btn-large waves-effect waves-light black orange-text z-depth-5">View Collection</a></b>
        {% else %}
          <b><a href="{% url 'account:register' %}" class="btn-large waves-effect waves-light black orange-text z-depth-5">Register</a></b>
          &nbsp;
          <b><a href="#" class="btn-large waves-effect waves-light black orange-text z-depth-5">log In</a></b>
        {% endif %}
      </div>
      <br><br>

    </div>
  </div>
  <div class="parallax"><img src="{% static 'common/background1.jpg' %}" alt="banner1"></div>
</div>

<!-- Card Links to Webpage -->
<div class="container">
  <div class="row">
    <div class="col s6 ">
      <div class="card hoverable black">
        <div class="card-image grey lighten-4">
          <a href="{% url 'gallery:art_toy' %}">
           <img src="{% static 'common/art_toy.jpg' %}" class="responsive-image">
          </a>
        </div>
        <div class="card-action center">
          <a href="{% url 'gallery:art_toy' %}">View by Art Toys</a>
        </div>
      </div>
    </div>
    <div class="col s6 ">
      <div class="card hoverable black">
        <div class="card-image">
          <a href="{% url 'gallery:artist'%}">
            <img src="{% static 'common/artist.jpg' %}" class="responsive-image">
          </a>
        </div>
        <div class="card-action center">
          <a href="{% url 'gallery:artist'%}">View by Artists</a>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Second Page Banner -->
<div class="parallax-container valign-wrapper">
  <div class="section no-pad-bot">
    <div class="container">
      <div class="row center">
        <h2 class="header col s12 orange-text"></h2>
      </div>
    </div>
  </div>
  <div class="parallax"><img src="{% static 'common/background1.jpg' %}" alt="banner2"></div>
</div>

<!-- Icon Summary Section -->
<div class="container">
  <div class="section">
    <div class="row">
      <div class="col s12 m6">
        <div class="icon-block">
          <h2 class="center brown-text"><i class="material-icons">flash_on</i></h2>
          <h5 class="center">Faster Art Toy Lookup</h5>
          <p class="light">No need to spend hours searching multiple social media accounts to be familiar with what's out there. </p>
        </div>
      </div>
      <div class="col s12 m6">
        <div class="icon-block">
          <h2 class="center brown-text"><i class="material-icons">settings</i></h2>
          <h5 class="center">Continuous Development </h5>
          <p class="light">We are still a work in progress and have a lot of idea to be implemented on this webpage in the future.</p>
        </div>
      </div>

    </div>
  </div>
</div>
{% endblock %}