laparagon/account/urls.py
from django.urls import path

from . import views

app_name = 'account'
urlpatterns = [
    #path('', views.profile_page, name='collection'),
    path('register/', views.register, name='register'),
    #path('profile/', views.profile_page, name='profile'),
    path('profile/collection/', views.collection_page, name='collection'),
    path('profile/wishlist/', views.wishlist_page, name='wishlist'),

    path('add/<slug:type_slug>/<slug:toy_slug>/', views.add_to_profile, name='add_to_profile'),
    path('remove/<slug:toy_slug>/', views.remove_from_collection, name='remove_from_collection'),
]

laparagon/gallery/urls.py
from django.urls import path

from . import views

app_name = 'gallery'

urlpatterns = [
    path('art_toy/', views.art_toy_page, name='art_toy'),
    path('art_toy/<slug:toy_slug>/', views.art_toy_detail, name='art_toy_detail'),
    path('art_toy_search/', views.art_toy_search, name='art_toy_search'),

    path('artist/', views.artist_page, name='artist'),
    path('artist/<slug:artist_slug>/', views.artist_detail, name='artist_detail'),
    path('artist_search/', views.artist_search, name='artist_search'),

    #path('base_model/', views.base_model_page, name='base_model'),
    path('base_model/<slug:base_slug>/', views.base_model_detail, name='base_model_detail'),

    path('organization/<slug:org_slug>/', views.organization_detail, name='organization_detail'),
    # path('artist/<slug:artist_slug>/', views.artist_detail, name='artist_detail'),
    # path('artist/<slug:artist_slug>/', views.artist_detail, name='artist_detail'),
]

laparagon/paragon/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('home/', views.home, name='home'),
    path('about/', views.about_us, name='about_us'),
    # Apps
    path('gallery/', include('gallery.urls')),
    path('authentication/', include('authentication.urls')),
    path('account/', include('account.urls')),
    # Admin
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

laparagon/gallery/models.py
from django.db import models
from django_countries.fields import CountryField
from image_cropping import ImageRatioField
from django.utils.text import slugify


def generate_filename(self, filename):
    if self.__class__.__name__ == 'ArtToyImage':
        name = "arttoy/%s/%s" % (self.art_toy.name, filename)
    elif self.__class__.__name__ == 'BaseModelImage':
        name = "basemodel/%s/%s" % (self.base_model.name, filename)
    else:
        name = "%s/%s/%s" % (self.__class__.__name__.lower(), self.name, filename)
    return name


class Organization(models.Model):

    FACEBOOK_GROUP = 'FBG'
    MANUFACTURER = 'MAN'
    RETAILER = 'RET'
    OTHER = 'OTH'
    TYPES = (
        (FACEBOOK_GROUP, 'Facebook Group'),
        (MANUFACTURER, 'Manufacturer'),
        (RETAILER, 'Retailer'),
        (OTHER, 'Other'),
    )

    name = models.CharField(max_length=128, unique=True)
    slug = models.SlugField(max_length=128, unique=True)
    established_on = models.DateField()
    type = models.CharField(max_length=3, choices=TYPES)
    email = models.EmailField(unique=True, blank=True, null=True)
    link = models.URLField(unique=True, blank=True, null=True)
    bio = models.TextField()
    logo = models.ImageField(upload_to=generate_filename)
    # auto
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Event(models.Model):
    name = models.CharField(max_length=128, unique=True)
    organized_by = models.ManyToManyField(Organization, blank=True)
    location = models.CharField(max_length=128, blank=True)
    date = models.DateField()
    link = models.URLField(unique=True, blank=True, null=True)

    def __str__(self):
        return self.name


class Artist(models.Model):
    # user = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL)
    name = models.CharField(max_length=128, unique=True)
    slug = models.SlugField(max_length=128, unique=True)
    alias = models.CharField(max_length=128, blank=True, help_text="Also known as (can be blank); please separate multiple aliases with a comma(,)")
    email = models.EmailField(unique=True, blank=True, null=True)
    logo = models.ImageField(upload_to=generate_filename)
    cropping = ImageRatioField('logo', '450x360')
    country = CountryField(default='PH')
    bio = models.TextField()
    facebook_link = models.URLField(unique=True, blank=True, null=True, default=None)
    instagram_link = models.URLField(unique=True, blank=True, null=True, default=None)
    twitter_link = models.URLField(unique=True, blank=True, null=True, default=None)
    website_link = models.URLField(unique=True, blank=True, null=True,default=None)
    # auto
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        if self.twitter_link == "":
            self.twitter_link = None
        super(Artist, self).save(*args, **kwargs)


#---- Base model of the figure
class BaseModel(models.Model):
    name = models.CharField(max_length=128, unique=True)
    slug = models.SlugField(max_length=128, unique=True)
    designer = models.ManyToManyField(Artist)
    description = models.TextField()
    thumbnail = models.ImageField(upload_to=generate_filename)
    cropping = ImageRatioField('thumbnail', '450x360')
    # auto
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class BaseModelImage(models.Model):
    base_model = models.ForeignKey(BaseModel, on_delete=models.CASCADE)
    image = models.ImageField(upload_to=generate_filename)
    created = models.DateTimeField(auto_now_add=True)


class ArtToy(models.Model):
    OFFICIAL = 'OFF'
    CUSTOM = 'CUS'
    COMMISSION = 'COM'
    TYPES = (
        (OFFICIAL, 'Official'),
        (CUSTOM, 'Custom'),
        (COMMISSION, 'Commission'),
    )
    # art toy details
    type = models.CharField(max_length=3, choices=TYPES, default='OFF')
    name = models.CharField(max_length=128, unique=True)
    slug = models.SlugField(max_length=128, unique=True)
    base_model = models.ManyToManyField(BaseModel, help_text="Please specify the base figure/s used")
    edition_size = models.PositiveIntegerField()
    dimensions = models.CharField(max_length=32, help_text="Please follow this pattern(Lx W x H) and specify the unit of measurement")
    medium = models.CharField(max_length=128, help_text="Materials that were used for the product")
    description = models.TextField(blank=True, help_text="Any relevant details of the art toy.")

    # contributor details
    artist = models.ManyToManyField(Artist)
    organization = models.ManyToManyField(Organization, blank=True, help_text="If there are other organizations involved that is not an artist. eg: Store, FB group, etc.")

    # release details
    event = models.ManyToManyField(Event, blank=True)
    is_auction = models.BooleanField(default=False, help_text="Please specify if this piece was auctioned off.")
    release_date = models.DateField()
    release_at = models.TextField(blank=True, help_text="Please input the links of where the art toy was released.")
    release_price = models.DecimalField(max_digits=9, decimal_places=2, help_text="Please put a value of 0 if the price is unknown.")

    # auto
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    thumbnail = models.ImageField(upload_to=generate_filename)
    cropping = ImageRatioField('thumbnail', '450x360')

    def __str__(self):
        return self.name


class ArtToyImage(models.Model):
    art_toy = models.ForeignKey(ArtToy, default=None, on_delete=models.CASCADE)
    image = models.ImageField(upload_to=generate_filename)
    created = models.DateTimeField(auto_now_add=True)

laparagon/gallery/views.py
from django.shortcuts import render, get_object_or_404
from .models import ArtToy, Artist, ArtToyImage, BaseModel, BaseModelImage, Organization
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def base_model_detail(request, base_slug):
    base_model = get_object_or_404(BaseModel, slug=base_slug)
    images = BaseModelImage.objects.filter(base_model=base_model)
    art_toys = ArtToy.objects.filter(base_model=base_model.id)

    paginator = Paginator(art_toys, 4)
    page = request.GET.get('page')
    try:
        art_toys = paginator.page(page)
    except PageNotAnInteger:
        art_toys = paginator.page(1)
    except EmptyPage:
        art_toys = paginator.page(paginator.num_pages)

    return render(request, 'gallery/base_model.html', {'base_model': base_model,
                                                       'art_toys' : art_toys,
                                                       'images' : images})


def art_toy_page(request):
    sort = request.GET.get("sort")
    art_type = request.GET.get("filter")

    type_list = ArtToy.objects.all().distinct('type')

    if sort:
        art_toys = sort_art_toy(sort)
    elif art_type:
        art_toys = filter_art_toy(art_type)
    else:
        art_toys =  ArtToy.objects.all()

    paginator = Paginator(art_toys, 4)
    page = request.GET.get('page')
    try:
        art_toys = paginator.page(page)
    except PageNotAnInteger:
        art_toys = paginator.page(1)
    except EmptyPage:
        art_toys = paginator.page(paginator.num_pages)

    return render(request, 'gallery/art_toy.html', {'art_toys': art_toys,
                                                    'type_list': type_list,
                                                    'nbar': 'art_toy',})


def filter_art_toy(art_type):
    art_toys = ArtToy.objects.filter(type=art_type)

    return art_toys



def sort_art_toy(sort):
    if sort == "title_asc":
        art_toys = ArtToy.objects.all().order_by('name')
    elif sort == "title_des":
        art_toys = ArtToy.objects.all().order_by('-name')
    elif sort == "date_asc":
        art_toys = ArtToy.objects.all().order_by('release_date')
    elif sort == "date_des":
        art_toys = ArtToy.objects.all().order_by('-release_date')
    else:
        art_toys = None

    return art_toys


def artist_page(request):
    sort = request.GET.get("sort")
    nationality = request.GET.get("filter")

    nationality_list = Artist.objects.all().distinct('country').order_by('country')

    if sort:
        artist_list = sort_artist(sort)
    elif nationality:
        artist_list = filter_artist(nationality)
    else:
        artist_list = Artist.objects.all()

    paginator = Paginator(artist_list, 8)
    page = request.GET.get('page')
    try:
        artists = paginator.page(page)
    except PageNotAnInteger:
        artists = paginator.page(1)
    except EmptyPage:
        artists = paginator.page(paginator.num_pages)

    return render(request, 'gallery/artist.html', {'artists': artists,
                                                   'nationality_list': nationality_list,
                                                   'nbar': 'artist',
                                                   'title': 'Artist'})


def filter_artist(nationality):
    artists = Artist.objects.filter(country=nationality)

    return artists



def sort_artist(sort):
    if sort == "name_asc":
        artists = Artist.objects.all().order_by('name')
    elif sort == "name_des":
        artists = Artist.objects.all().order_by('-name')
    else:
        artists = None

    return artists


def art_toy_detail(request, toy_slug):
    toy = get_object_or_404(ArtToy,slug=toy_slug)
    images = ArtToyImage.objects.filter(art_toy=toy.id)

    return render(request, 'gallery/art_toy_detail.html', {'toy': toy,
                                                       'images': images,})


def artist_detail(request, artist_slug):
    artist = get_object_or_404(Artist, slug=artist_slug)
    base_models = BaseModel.objects.filter(designer=artist)

    paginator = Paginator(base_models, 4)
    page = request.GET.get('page')
    try:
        base_models = paginator.page(page)
    except PageNotAnInteger:
        base_models = paginator.page(1)
    except EmptyPage:
        base_models = paginator.page(paginator.num_pages)

    return render(request, 'gallery/artist_detail.html', {'artist': artist,
                                                          'base_models': base_models,})


def art_toy_search(request):
    query = request.GET.get("q")
    if query:
        art_toys_list = ArtToy.objects.filter(Q(name__icontains=query) |
                                              Q(artist__name__icontains=query)).distinct()

        paginator = Paginator(art_toys_list, 4)
        page = request.GET.get('page')
        try:
            art_toys = paginator.page(page)
        except PageNotAnInteger:
            art_toys = paginator.page(1)
        except EmptyPage:
            art_toys = paginator.page(paginator.num_pages)
    else:
        art_toys = None

    sort = request.GET.get("sort")
    if sort:
        art_toys = sort_art_toy(request, sort)

    return render(request, 'gallery/art_toy.html', {'art_toys': art_toys,
                                                    'nbar': 'gallery',})


def artist_search(request):
    query = request.GET.get("q")
    if query:
        artists = Artist.objects.filter(Q(name__icontains=query) |
                                        Q(alias__icontains=query)).distinct()
        paginator = Paginator(artists, 3)
        page = request.GET.get('page')
        try:
            artists = paginator.page(page)
        except PageNotAnInteger:
            artists = paginator.page(1)
        except EmptyPage:
            artists = paginator.page(paginator.num_pages)
    else:
        artists = None
    return render(request, 'gallery/artist.html', {'artists': artists,
                                                   'nbar': 'gallery',})


def organization_detail(request, org_slug):
    organization = get_object_or_404(Organization, slug=org_slug)

    return render(request, 'gallery/organization.html',{'organization': organization})

laparagon/gallery/templates/gallery/art_toy.html
{% extends "base_site.html" %}
{% load static %}
{% load cropping %}

{% block title %} | Art Toys {% endblock title%}

{% block content %}
<div class="row indigo lighten-5">
  <div class="col s12 center ">
    <h4 class="black-text"><b>Art Toys</b></h4>
  </div>
</div>

<div class="container">
  <div class="row">
    <!-- Search Art Toy Form -->
    <div class="col s12 m4 l6 left">
      <form method="GET" action="{% url 'gallery:art_toy_search' %}">
        <div class="input-field">
          <input id="search" type="search" name="q" placeholder="Search art toys by title or artist name" value="{{ request.GET.q }}" required>
          <i class="material-icons">close</i>
          <label>Search</label>
        </div>
      </form>
    </div>

    <!-- Filter Dropdown -->
    <div class="col s12 m4 l3">
      <div class="input-field col s12">
        <form method="GET">
        <select name="filter" onchange="form.submit();">
          <option value="" disabled selected>Choose your option</option>
          {% for t in type_list %}
            <option value="{{ t.type }}"{% if request.GET.filter == t %} selected {% endif %}>{{ t.get_type_display }}</option>
          {% endfor %}
        </select>
        <label>Filter by</label>
        </form>
      </div>
    </div>

    <!-- Sort dropdown -->
    <div class="col s12 m4 l3">
      <div class="input-field col s12">
        <form method="GET">
        <select name="sort" onchange="form.submit();">
          <option value="" disabled selected>Choose your option</option>
          <option value="title_asc" {% if request.GET.sort == "title_asc" %} selected {% endif %}>Title: A- Z</option>
          <option value="title_des" {% if request.GET.sort == "title_des" %} selected {% endif %}>Title: Z - A</option>
          <option value="date_asc" {% if request.GET.sort == "date_asc" %} selected {% endif %}>Released: new to old</option>
          <option value="date_des" {% if request.GET.sort == "date_des" %} selected {% endif %}>Released: old to new</option>
        </select>
        <label>Sort by</label>
        </form>
      </div>
    </div>
  </div>

  <div class="row">
    {% if not art_toys %}
      <h5 class="red-text">

        {% if request.GET.q %}
          No  art toys found that matches "{{request.GET.q}}".
        {% else %}
          No Art Toys Found.
        {% endif %}
      </h5>
    {% else %}
      <!-- Art toys for loop-->
      {% for a in art_toys %}
        <a href="{% url 'gallery:art_toy_detail' toy_slug=a.slug %}">
          <div class="col s12 m6 l4 xl3">
            <div class="card small hoverable">
              <div class=" card-image">
                <img class="responsive-img" src="{% cropped_thumbnail a 'cropping' %}">
              </div>
              <div class="card-content black center-align ">
                <span class="orange-text flow-text ">{{ a.name }}</span>

                <!-- Add Option if User is Logged In -->
                {% if user.is_authenticated %}
                  <!-- Modal Trigger -->
                  <a class="btn-floating waves-effect waves-light right modal-trigger" href="#add-{{ a.id }}">
                    <i class="material-icons orange black-text hoverable">add</i>
                  </a>

                  <!-- Modal Structure -->
                  <div id="add-{{ a.id }}" class="modal">
                    <div class="modal-content">
                      <a href="#" class="modal-close right" onclose="modal.close();">
                        <i class="material-icons">close</i>
                      </a>
                      <h4>Where do you wish to add <b>{{ a.name }}</b>?</h4>
                      <img class="responsive-img" src="{% cropped_thumbnail a 'cropping' %}">
                    </div>

                    <div class="modal-footer">
                      <div class="row center-align">
                        <div class="col s6 m3 offset-m3 l4 offset-l2">
                          <a href="{% url 'account:add_to_profile' type_slug='collection' toy_slug=a.slug %}" class="modal-close waves-effect waves-light green btn">
                            Collection
                          </a>
                        </div>
                        <div class="col s6 m3 l4">
                          <a href="{% url 'account:add_to_profile' type_slug='wishlist' toy_slug=a.slug %}" class="modal-close waves-effect waves-light blue btn">
                            Wishlist
                          </a>
                        </div>
                      </div>
                    </div>
                  </div>
                {% endif %}

              </div>
            </div>
          </div>
        </a>
      {% endfor %}
    {% endif %}
  </div>
</div>

<!-- pagination -->
<div class="container center">
  {% if art_toys.has_other_pages %}
    <ul class="pagination">
      <!-- back button -->
      {% if art_toys.has_previous %}
        <li class="waves-effect">
          <a href="?q={{ request.GET.q }}&filter={{request.GET.filter}}&sort={{ request.GET.sort }}&page={{ art_toys.previous_page_number }}" >
          <i class="material-icons">chevron_left</i></a>
        </li>
      {% else %}
        <li class="disabled"><a href="#"><i class="material-icons">chevron_left</i></a></li>
      {% endif %}

      <!-- middle section -->
      {% for i in art_toys.paginator.page_range %}
        {% if i <= art_toys.number|add:3 and i >= art_toys.number|add:-3 %}
          {% if art_toys.number == i %}
            <li class="active purple"><a href="#!">{{ i }}</a></li>
          {% else %}
            <li><a href="?q={{ request.GET.q }}&filter={{request.GET.filter}}&sort={{ request.GET.sort }}&page={{ i }}" >{{ i }}</a></li>
          {% endif %}
        {% endif %}
      {% endfor %}

      <!-- next button -->
      {% if art_toys.has_next %}
        <li class="waves-effect">
          <a href="?q={{ request.GET.q }}&page={{ art_toys.next_page_number }}" >
          <i class="material-icons">chevron_right</i></a>
        </li>
      {% else %}
        <li class="disabled"><a href="#"><i class="material-icons">chevron_right</i></a></li>
      {% endif %}
    </ul>
  {%endif%}
</div>
{% endblock %}



laparagon/gallery/templates/gallery/art_toy_detail.html
{% extends "base_site.html" %}

{% block title %} | {{toy.name}} {% endblock title%}

{% block content %}
<!-- Art Toy Name and Creators -->
<div class="row indigo lighten-5">
  <div class="col s12 center">
    <h4 class="black-text"><b>{{ toy.name }}</b></h4>
    <h6> by
      <!-- Artists involved for loop -->
      {% for artist in toy.artist.all %}
        {% if forloop.counter == 1 %}
          <a href="{% url 'gallery:artist_detail' artist_slug=artist.slug %}">{{ artist.name }} </a>
        {% else %}
          x <a href="{% url 'gallery:artist_detail' artist_slug=artist.slug %}"> {{ artist.name }} </a>
        {% endif %}
      {% endfor %}

      <!-- Organizations involved for loop -->
      {% for organization in toy.organization.all %}
        x <a href="{% url 'gallery:organization_detail' org_slug=organization.slug %}"> {{ organization.name }} </a>
      {% endfor %}
    </h6>
  </div>
</div>

<div class="container">
  <div class="row">
    <!-- Carousel display with enlarge photo -->
    <div class="col s12 l5">
      <div class="carousel">
        <a class="carousel-item" href="#"><img class="materialboxed responsive-img" src="{{ toy.thumbnail.url }}"></a>
      {% for img in images %}
        {% if img.image %}
          <a class="carousel-item" href="#"><img class="materialboxed responsive-img" src="{{ img.image.url }}"></a>
        {% endif %}
      {% endfor %}
        </div>
      <br>
    </div>
    <!-- Tabs for Details -->
    <div class="col s12 l7">
      <ul class="tabs">
        <li class="tab col s6"><a href="#art_toy_details">Art Toy Details</a></li>
        <li class="tab col s6"><a href="#release_details">Release Details</a></li>
      </ul><br>
      <!-- Art Toy Details Table -->
      <div id="art_toy_details" class="col s12">
        <table class="striped">
          <tbody class="black-text">
            <tr>
              <td><b> Base Model </b></td>
              <td>
                {% for base_model in toy.base_model.all %}
                  {% if forloop.counter == 1 %}
                    <a href="{% url 'gallery:base_model_detail' base_slug=base_model.slug  %}">{{ base_model.name }}</a>
                  {% else %}
                    , <a href="{% url 'gallery:base_model_detail' base_slug=base_model.slug  %}">{{ base_model.name }}</a>
                  {% endif %}
                {% endfor %}
              </td>
            </tr>
            <tr>
              <td><b> Medium </b></td>
              <td> {{ toy.medium }} </td>
            </tr>
            <tr>
              <td><b> Edition Size </b></td>
              <td>
                {% if toy.edition_size == 1 %}
                one-off
                {% else %}
                  {{ toy.edition_size }}
                {% endif %}
              </td>
            </tr>
            <tr>
              <td><b> Dimensions </b></td>
              <td> {{ toy.dimensions }} </td>
            </tr>

            {% if toy.description %}
            <tr>
              <td><b> Description </b></td>
              <td> {{ toy.description|urlize|linebreaks }} </td>
            </tr>
            {% endif %}
          </tbody>
        </table>
    </div>
    <!-- Release Details -->
    <div id="release_details" class="col s12">
      <table class="striped">
        <tbody class="black-text">
          <tr>
            <td><b> Type </b></td>
            <td>
              <span class="tooltipped" data-position="right" data-tooltip="
                {% if toy.type == "OFF" %}
                  produced in large quantities and made available to the public
                {% elif toy.type == "CUS" %}
                  typically one-off; customized outside of the general series and made available to the public
                {% elif toy.type == "COM" %}
                  specially created for a private collector
                {% endif %}">
                {{ toy.get_type_display }}
              </span>
            </td>
          </tr>
          <tr>
            <td><b> Released Price</b>
              {% if toy.is_auction %} <br><span class="grey-text">(via auction)</span>{% endif %}
            </td>
            <td>
              {% if toy.release_price == 0 %}
                N/A
              {% else %}
                &#x20B1; {{ toy.release_price }}
              {% endif %}
            </td>
          </tr>
          <tr>
            <td><b> Released On </b></td>
            <td> {{ toy.release_date }} </td>
          </tr>

          {% if toy.release_at %}
          <tr>
            <td><b> Released At </b></td>
            <td> {{ toy.release_at|urlize|linebreaks }} </td>
          </tr>
          {% endif %}

        </tbody>
      </table>
    </div>
  </div>



    <!-- End of Table -->
  </div>
</div>
{% endblock %}

laparagon/gallery/templates/gallery/artist.html
{% extends "base_site.html" %}
{% load static %}
{% load cropping %}

{% block title %} | Artists {% endblock title%}

{% block content %}
<div class="row indigo lighten-5">
  <div class="col s12 center">
    <h4 class="black-text"><b>Artists</b></h4>
  </div>
</div>

<div class="container">
  <div class="row">
    <!-- Search artist form -->
    <div class="col s12 m4 l6 left">
      <form method="GET" action="{% url 'gallery:artist_search' %}">
        <div class="input-field">
          <input type="search" name="q" placeholder="Search by artist name" value="{{ request.GET.q }}" required>
          <i class="material-icons">close</i>
          <label>Search</label>
        </div>
      </form>
    </div>

    <!-- Filter Nationality Dropdown -->
    {% if nationality_list %}
      <div class="col s12 m4 l3">
        <div class="input-field col s12">
          <form method="GET">
          <select name="filter" onchange="form.submit();">
            <option value="" disabled selected>Choose your option</option>
            {% for n in nationality_list %}
              <option value="{{ n.country }}"{% if request.GET.filter == n.country %} selected {% endif %}>{{ n.country.name }}</option>
            {% endfor %}
          </select>
          <label>Filter by Nationality</label>
          </form>
        </div>
      </div>
    {% endif %}

    <!-- Sort Dropdown -->
    <div class="col s12 m4 l3 right">
      <div class="input-field col s12">
        <form method="GET">
        <select name="sort" onchange="form.submit();">
          <option value="" disabled selected>Choose your option</option>
          <!--<option value="price_asc" {% if request.GET.sort == "price_asc" %} selected {% endif %}>Price: low to high</option>
          <option value="price_des" {% if request.GET.sort == "price_des" %} selected {% endif %}>Price: high to low</option>-->
          <option value="name_asc" {% if request.GET.sort == "name_asc" %} selected {% endif %}>Name: A- Z</option>
          <option value="name_des" {% if request.GET.sort == "name_des" %} selected {% endif %}>Name: Z - A</option>
        </select>
        <label>Sort by</label>
        </form>
      </div>
    </div>
  </div>


  <div class="row">
    {% if not artists %}
      <h5 class="red-text">
        {% if request.GET.q %}
          No artists found that matches "{{request.GET.q}}"
        {% else %}
          No Artists Found.
        {% endif %}
      </h5>
    {% else %}
      <!-- Artists for loop -->
      {% for artist in artists %}
        <div class="col s12 m6 l4 xl3">
          <a href="{% url 'gallery:artist_detail' artist_slug=artist.slug %}">
            <div class="card small hoverable">
              <div class="card-image">
                   <img class="responsive-img" src="{% cropped_thumbnail artist 'cropping' %}">
              </div>
              <div class="card-content black center-align">
                <span class="orange-text flow-text ">{{ artist.name }}</span>
              </div>
            </div>
          </a>
        </div>
      {% endfor %}
    {% endif %}
  </div>
</div>

<!-- Pagination -->
<div class="container center">
  {% if artists.has_other_pages %}
    <ul class="pagination">
      <!-- back button -->
      {% if artists.has_previous %}
        <li class="waves-effect">
          <a href="?sort={{ request.GET.sort }}&page={{ artists.previous_page_number }}" >
          <i class="material-icons">chevron_left</i></a>
        </li>
      {% else %}
        <li class="disabled"><a href="#"><i class="material-icons">chevron_left</i></a></li>
      {% endif %}

      <!-- middle section -->
      {% for i in  artists.paginator.page_range %}
        {% if i <= artists.number|add:3 and i >= artists.number|add:-3 %}
          {% if artists.number == i %}
            <li class="active purple"><a href="#!">{{ i }}</a></li>
          {% else %}
            <li><a href="?sort={{ request.GET.sort }}&page={{ i }}" >{{ i }}</a></li>
          {% endif %}
        {% endif %}
      {% endfor %}

      <!-- next button -->
      {% if artists.has_next %}
        <li class="waves-effect">
          <a href="?sort={{ request.GET.sort }}&page={{ artists.next_page_number }}" >
          <i class="material-icons">chevron_right</i></a>
        </li>
      {% else %}
        <li class="disabled"><a href="#"><i class="material-icons">chevron_right</i></a></li>
      {% endif %}
    </ul>
  {%endif%}
</div>
{% endblock %}